import { Inter, Mandali } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "./sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen h-full bg-background antialiased flex",
          inter.className
        )}
      >
        <Sidebar />
        <main className="flex-1 flex flex-col">{children}</main>
      </body>
    </html>
  );
}
